### ISSUE TITLE
delete cookie example

### ISSUE THREAD

**Issue by vyaspranjal33** [punit-agarwal/PHP-Concepts#2]
<?php
// set the expiration date to one hour ago
setcookie("user", "", time() - 3600);
?>
<html>
<body>

<?php
echo "Cookie 'user' is deleted.";
?>

</body>
</html>

**Comment by punit-agarwal** [comment]
What's the issue?
Please write the description for your issue.

**Comment by vyaspranjal33** [comment]
sorry it was mistakenly opens
